### ISSUE TITLE
SSL Error [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by ot0tot** [aclytle/Motorola-Modem-Reboot#1]
Not working on my MB8600:

> Traceback (most recent call last):
>   File "modem_reboot.py", line 171, in <module>
>     r = h.login(host, password)
>   File "modem_reboot.py", line 64, in login
>     r = self._login_request(host)
>   File "modem_reboot.py", line 39, in _login_request
>     r = self.s.post(url, headers=headers, data=payload, stream=True)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 578, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 530, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 665, in send
>     history = [resp for resp in gen] if allow_redirects else []
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 245, in resolve_redirects
>     **adapter_kwargs
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 643, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 514, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.100.1', port=443): Max retries exceeded with url: /HNAP1/ (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),))

**Comment by aclytle** [comment]
This may have been fixed with 4b4d18c0408a26b3f9ac7ba00f59e9a99c9b3b82

Try running with the new --noverify option.
